### ISSUE TITLE
Exception when version not present in Python manifest

### ISSUE THREAD

**Issue by nickcampbell18** [gocardless/bump-core#4]
We've had an error via Sentry from bump:

```
JSON::ParserError: 765: unexpected token at ''
  from json/common.rb:156:in `parse'
  from json/common.rb:156:in `parse'
  from bump/update_checkers/python.rb:12:in `latest_version'
  from bump/update_checkers/base.rb:16:in `needs_update?'
  from /app/app/workers/dependency_updater.rb:62:in `update_dependency!'
  from /app/app/workers/dependency_updater.rb:33:in `perform'
```

It comes from here:
```ruby
        @latest_version ||=
          begin
            url = "https://pypi.python.org/pypi/#{dependency.name}/json"
            JSON.parse(Excon.get(url).body)["info"]["version"]
          end
      end
```

```ruby
# job args
{
  dependency: {'language': 'python', 'version': '1.0.13', 'name': 'sqlalchemy', 'previous_version': nil}, 
  dependency_files: [Filtered], 
  repo: {'commit': 'ca4cd6230ce6abcxxxxx24e42d89cfad6df3ffbb', 'name': 'gocardless/xxxx', 'language': 'python'}
}
```

I'm guessing that Excon.get(..) is returning an empty response, as `https://pypi.python.org/pypi/SQLAlchemy/json` includes this metadata?

**Comment by nickcampbell18** [comment]
@hmac just wanted to make sure we didn't drop this - I've seen this Sentry come around before.

**Comment by hmac** [comment]
So https://pypi.python.org/pypi/sqlalchemy/json redirects to https://pypi.python.org/pypi/SQLAlchemy/json (notice the case change) - I wonder if Excon isn't following the redirect?

**Comment by greysteil** [comment]
I'll take a look at this if you guys want

**Comment by greysteil** [comment]
And yep, it's totally that @hmac - PR incoming.

**Comment by hmac** [comment]
:+1:
